Parameters:
 bktname:
   Type: String
   Description: Name of bucket

Resources:
  s3bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref bktname
      VersioningConfiguration:
        Status: Suspended
